# curl -i http://httpbin.org/ip
###
GET http://localhost:10/addpair?currency=CHR&title=Pair1
###
GET http://localhost:10/onpair?id=P_CHR
###
GET http://localhost:10/addpair?currency=ENJ&title=Pair1
###
GET http://localhost:10/onpair?id=P_ENJ
###
GET http://localhost:10/addpair?currency=PORTO&title=Pair1
###
GET http://localhost:10/onpair?id=P_PORTO
###
